### ISSUE TITLE
Centre on screen vertically

### ISSUE THREAD

**Issue by Drmillsy** [zjosua/anki-mc#115]
*I would love an option to centre the front and back of the cards on teh centre of the screen vertically, its already horizontally aligned but it sits at the top of the screen.

**Comment by 3ter** [comment]
You could use something like this: https://www.reddit.com/r/Anki/comments/ek60gl/gif_a_way_to_center_the_contents_on_your_cards/

You have to edit the note type:
- For both front and back you enclose the contents with `div`s e.g. like this on the front
```html
<div class="vertically_centered">

{{#Title}}<h3 id="myH1">{{Title}}</h3>{{/Title}}
{{#Question}}<p>{{Question}}</p>{{/Question}}

<div class="tappable">
    <table style="border: 1px solid black" id="qtable"></table>
</div>

<div class="hidden" id="Q_solutions">{{Answers}}</div>
<div class="hidden" id="Card_Type">{{QType (0=kprim,1=mc,2=sc)}}</div>

<div class="hidden" id="Q_1">{{Q_1}}</div>
<div class="hidden" id="Q_2">{{Q_2}}</div>
<div class="hidden" id="Q_3">{{Q_3}}</div>
<div class="hidden" id="Q_4">{{Q_4}}</div>
<div class="hidden" id="Q_5">{{Q_5}}</div>

</div>
```
- And in the styling tab you add the respective css class
```css
.vertically_centered:not(.mobile) {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: -webkit-box;
  -webkit-box-align: stretch;
  -webkit-box-pack: center;
  -webkit-box-orient: vertical;
}
```
