### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by As-Salt** [zjosua/anki-mc#9]
I can't change the text alignment to center

**Comment by zjosua** [comment]
Change `text-align: left;` to `text-align: center;` and add
```css
table {
 display: inline-block;
 text-align: left
}
```
